export const pollyOptions = {
  cy: {code:"cy-GB", voiceId:'Gwyneth'},
  da: {code:"da-DK", voiceId:'Sofie'},
  de: {code:"de-DE", voiceId:'Vicki'},
  en: {code:"en-GB", voiceId:'Amy'},
  es: {code:"es-ES", voiceId:'Conchita'},
  fr: {code:"fr-FR", voiceId:'Léa'},
  is: {code:"is-IS", voiceId:'Dora'},
  it: {code:"it-IT", voiceId:'Bianca'},
  ja: {code:"ja-JP", voiceId:'Tomoko'},
  hi: {code:"hi-IN", voiceId:'Kajal'},
  ko: {code:"ko-KR", voiceId:'Seoyeon'},
  nb: {code:"nb-NO", voiceId:'Ida'},
  nl: {code:"nl-NL", voiceId:'Laura'},
  pl: {code:"pl-PL", voiceId:'Ewa'},
  pt: {code:"pt-BR", voiceId:'Camila'},
  ro: {code:"ro-RO", voiceId:'Carmen'},
  sv: {code:"sv-SE", voiceId:'Astrid'},
  tr: {code:"tr-TR", voiceId:'Filiz'},
  ca: {code:"ca-ES", voiceId:'Arlet'},
  ar: {code:"ar-AE", voiceId:'Zeina'},
  fi: {code:"fi-FI", voiceId:'Suvi'},
  cs: {code:"cs-CZ", voiceId:'Jitka'},
}

