import Head from 'next/head';
import Header from 'components/header';
import ListForm from 'components/listForm';
import useStore, { State }  from 'store/lists';

import styles from 'styles/pages/Create.module.css';

export default function Create() {

  const currentList = useStore((state: State) => state.currentList);

  return (
    <div className={styles.container}>
      <Head>
        <title>Fluent</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header/>
      <main className={styles.main}>
        <h1 className={styles.title}>
          Create List
        </h1>
        <ListForm item={currentList}/>
      </main>
    </div>
  )
}
