import Head from 'next/head';
import Header from 'components/header';
import ListForm from 'components/listForm';
import useStore, { State }  from 'store/lists';
import SavingScreen from 'components/savingScreen';
import { useIsServerSideMobile } from 'context/serverSideMobile';
import { getIsSsrMobile } from 'helpers/serverSideMobile';
import { GetServerSidePropsContext } from "next";
import { withAuth } from 'components/withAuth';

import styles from 'styles/pages/Create.module.css';

export async function getServerSideProps(context: GetServerSidePropsContext) {
  return {
    props: {
      isSsrMobile: getIsSsrMobile(context)
    }
  };
}

function Create() {

  const currentList = useStore((state: State) => state.currentList);
  const isSaving = useStore((state: State) => state.isSaving);

  const isTabletOrMobile = useIsServerSideMobile();

  return (
    <div className={styles.container}>
      <Head>
        <title>Fluent</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header/>
      <main className={styles.main}>
        <h1 className={styles.title}>
          Create List
        </h1>
        <ListForm item={currentList} isTabletOrMobile={isTabletOrMobile}/>
      </main>
      {isSaving && <SavingScreen/>}
    </div>
  )
}

export default withAuth(Create);
