import Head from 'next/head';
import { GetServerSidePropsContext } from "next";
import Header from 'components/header';
import AutoTranslate from 'components/settings/autoTranslate';
import Lenguage from 'components/settings/language';
import SavingScreen from 'components/savingScreen';
import useSettingsStore, { State as SettingsState } from 'store/settings';
import { getIsSsrMobile } from 'helpers/serverSideMobile';
import TranslateTo from 'components/settings/translateTo';

import styles from 'styles/pages/Settings.module.css';

export async function getServerSideProps(context: GetServerSidePropsContext) {
  return {
    props: {
      isSsrMobile: getIsSsrMobile(context)
    }
  };
}

export default function Settings() {
  const isSaving = useSettingsStore((state: SettingsState) => state.isSaving);
  return (
    <div className={styles.container}>
      <Head>
        <title>Fluent</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header/>
      <main className={styles.main}>
        <TranslateTo/>
        <AutoTranslate/>
        <Lenguage/>
      </main>
      {isSaving && <SavingScreen/>}
    </div>
  )
}
