import Head from 'next/head';
import Header from 'components/header';
import AutoTranslate from 'components/settings/autoTranslate';
import Lenguage from 'components/settings/language';

import styles from 'styles/pages/Settings.module.css';

export default function Settings() {

  return (
    <div className={styles.container}>
      <Head>
        <title>Fluent</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header/>
      <main className={styles.main}>
        <AutoTranslate/>
        <Lenguage/>
      </main>
    </div>
  )
}
